import type { Therapist } from "../components/TherapistSection";

/**
 * Six therapists on each area page — three Russian, three Indian.
 *
 * Generated so two rules hold by construction: no photograph appears on two
 * pages anywhere on the site, and no therapist name repeats (including against
 * the home page roster). Hero backgrounds use Rawimages 1-17; this file uses
 * 18-61 plus the girl_russian/girl_indian portraits the home page does not.
 */
export type AreaRoster = {
  /** Sub-heading above the grid, written per area. */
  intro: string;
  therapists: Therapist[];
};

export const AREA_THERAPISTS: Record<string, AreaRoster> = {
  "/spa-in-mahipalpur/": {
    intro:
      "Every therapist below works from the Defence Enclave building itself — this is the premises, not a catchment. Ask for anyone by name when you call.",
    therapists: [
      {
        img: "/home_images/girl_russian/r5.jpeg",
        name: "Alina",
        tag: "Russian Banya",
        years: "7 Years · Certified",
        desc: "Alina runs the full venik cycle — steam, birch, cold plunge, rest — and reads how much heat a guest can take rather than working to a fixed clock.",
        price: "₹3,500",
        duration: "90 min",
        origin: "russian",
      },
      {
        img: "/home_images/girl_russian/r6.jpeg",
        name: "Karina",
        tag: "Deep Tissue",
        years: "6 Years · Certified",
        desc: "Karina works chronic shoulder and lower-back patterns layer by layer. Most of her repeat guests sit at a desk all week.",
        price: "₹4,400",
        duration: "90 min",
        origin: "russian",
      },
      {
        img: "/home_images/girl_russian/r7.jpeg",
        name: "Alisa",
        tag: "Hot Stone",
        years: "5 Years · Certified",
        desc: "Alisa places basalt along the spine at 50–55°C and works it in, which reaches deeper tissue faster than hands alone.",
        price: "₹3,600",
        duration: "75 min",
        origin: "russian",
      },
      {
        img: "/home_images/girl_indian/i6.jpeg",
        name: "Divya",
        tag: "Aromatherapy",
        years: "5 Years · Certified",
        desc: "Divya blends the oil after asking about your sleep and stress rather than handing over a menu. Her sessions run gentle and slow.",
        price: "₹3,000",
        duration: "60 min",
        origin: "indian",
      },
      {
        img: "/home_images/girl_indian/i7.jpeg",
        name: "Trisha",
        tag: "Swedish Massage",
        years: "6 Years · Certified",
        desc: "Trisha takes most first bookings at the premises — unhurried, full-body, and the whole advertised hour on the table.",
        price: "₹2,800",
        duration: "60 min",
        origin: "indian",
      },
      {
        img: "/home_images/girl_indian/i8.jpeg",
        name: "Nikita",
        tag: "Couples Suite",
        years: "7 Years · Certified",
        desc: "Nikita runs the couples suite here, with two therapists working in sync and Banya access included.",
        price: "₹7,500",
        duration: "120 min",
        origin: "indian",
      },
    ],
  },
  "/spa-in-aerocity/": {
    intro:
      "The therapists who take most of our Aerocity hotel bookings — used to tight schedules, late arrivals and long-haul bodies.",
    therapists: [
      {
        img: "/home_images/girl_russian/r8.jpeg",
        name: "Larisa",
        tag: "Long-Haul Recovery",
        years: "8 Years · Certified",
        desc: "Larisa treats the specific stiffness eleven hours in economy produces: hip flexors, thoracic spine, neck.",
        price: "₹3,600",
        duration: "75 min",
        origin: "russian",
      },
      {
        img: "/home_images/girl_russian/r9.jpeg",
        name: "Milana",
        tag: "Late-Night Banya",
        years: "6 Years · Certified",
        desc: "Milana works the 11 PM to 4 AM window, which is when the Aerocity hotel strip actually calls us.",
        price: "₹3,500",
        duration: "90 min",
        origin: "russian",
      },
      {
        img: "/home_images/girl_russian/r10.jpeg",
        name: "Snezhana",
        tag: "Deep Tissue",
        years: "7 Years · Certified",
        desc: "Snezhana handles the conference-week bookings — shoulders and lower back after three days in a chair.",
        price: "₹4,400",
        duration: "90 min",
        origin: "russian",
      },
      {
        img: "/home_images/girl_indian/i9.jpeg",
        name: "Ishita",
        tag: "Reflexology",
        years: "5 Years · Certified",
        desc: "Ishita works the feet and hands after a long sector. Guests walking off a night flight tend to book her first.",
        price: "₹2,200",
        duration: "60 min",
        origin: "indian",
      },
      {
        img: "/home_images/girl_indian/i10.jpeg",
        name: "Tanvi",
        tag: "Swedish Massage",
        years: "6 Years · Certified",
        desc: "Tanvi keeps a steady medium pressure end to end — the right booking when you want to sleep afterwards.",
        price: "₹2,800",
        duration: "60 min",
        origin: "indian",
      },
      {
        img: "/home_images/girl_indian/i11.jpeg",
        name: "Bhavya",
        tag: "Aromatherapy",
        years: "4 Years · Certified",
        desc: "Bhavya builds a blend for time-zone recovery rather than general relaxation, which is a different oil entirely.",
        price: "₹3,000",
        duration: "60 min",
        origin: "indian",
      },
    ],
  },
  "/spa-in-delhi/": {
    intro:
      "Guests travelling in from across Delhi usually come for the Banya, so these are the therapists trained to run it properly.",
    therapists: [
      {
        img: "/home_images/girl_russian/r11.jpeg",
        name: "Vera",
        tag: "Russian Banya",
        years: "9 Years · Certified",
        desc: "Vera trained in the method rather than learning it from a manual. She sets the steam, works the venik and calls the rest cycle.",
        price: "₹3,500",
        duration: "90 min",
        origin: "russian",
      },
      {
        img: "/Rawimages/russianspacenterimage18.webp",
        name: "Nadia",
        tag: "Couples Banya",
        years: "7 Years · Certified",
        desc: "Nadia leads the couples Banya ritual — two therapists, synchronised timing, the suite to yourselves throughout.",
        price: "₹9,500",
        duration: "150 min",
        origin: "russian",
      },
      {
        img: "/Rawimages/russianspacenterimage19.webp",
        name: "Valeria",
        tag: "Russian Banya",
        years: "6 Years · Certified",
        desc: "Valeria handles the second and third heat cycles, which is where most guests decide the Banya was worth the drive.",
        price: "₹3,500",
        duration: "90 min",
        origin: "russian",
      },
      {
        img: "/home_images/girl_indian/i12.jpeg",
        name: "Rhea",
        tag: "Hot Stone",
        years: "5 Years · Certified",
        desc: "Rhea pairs heated basalt with deep tissue for guests who want the longer, warmer version of both.",
        price: "₹3,600",
        duration: "75 min",
        origin: "indian",
      },
      {
        img: "/home_images/girl_indian/i13.jpeg",
        name: "Charu",
        tag: "Thai Massage",
        years: "6 Years · Certified",
        desc: "Charu works oil-free acupressure and assisted stretching — guests leave lengthened rather than drowsy.",
        price: "₹3,200",
        duration: "75 min",
        origin: "indian",
      },
      {
        img: "/home_images/girl_indian/i14.jpeg",
        name: "Radhika",
        tag: "Ayurvedic Abhyanga",
        years: "8 Years · Certified",
        desc: "Radhika follows the classical Abhyanga sequence with warm herbal oil and a long scalp finish.",
        price: "₹3,800",
        duration: "90 min",
        origin: "indian",
      },
    ],
  },
  "/spa-in-dwarka/": {
    intro:
      "The therapists our Dwarka regulars book by name — most arrive on a weekday evening after the Link Road run.",
    therapists: [
      {
        img: "/Rawimages/russianspacenterimage20.webp",
        name: "Sofia",
        tag: "Deep Tissue",
        years: "6 Years · Certified",
        desc: "Sofia is the name Dwarka guests ask for when something has hurt for months rather than days.",
        price: "₹4,400",
        duration: "90 min",
        origin: "russian",
      },
      {
        img: "/Rawimages/russianspacenterimage21.webp",
        name: "Darina",
        tag: "Russian Banya",
        years: "5 Years · Certified",
        desc: "Darina runs the Banya for guests making the trip specifically for it, which is most of the Dwarka bookings.",
        price: "₹3,500",
        duration: "90 min",
        origin: "russian",
      },
      {
        img: "/Rawimages/russianspacenterimage22.webp",
        name: "Ulyana",
        tag: "Sports Recovery",
        years: "7 Years · Certified",
        desc: "Ulyana works with the Sector 10 gym crowd — trigger-point release and stretching rather than a relaxation hour.",
        price: "₹3,600",
        duration: "90 min",
        origin: "russian",
      },
      {
        img: "/Rawimages/russianspacenterimage41.webp",
        name: "Naina",
        tag: "Ayurvedic Abhyanga",
        years: "7 Years · Certified",
        desc: "Naina works warm herbal oil in the traditional rhythmic sequence, finishing with scalp and marma points.",
        price: "₹3,800",
        duration: "90 min",
        origin: "indian",
      },
      {
        img: "/Rawimages/russianspacenterimage42.webp",
        name: "Sanya",
        tag: "Swedish Massage",
        years: "4 Years · Certified",
        desc: "Sanya takes most first-time Dwarka bookings — nothing sold to you on the table, just the hour you paid for.",
        price: "₹2,800",
        duration: "60 min",
        origin: "indian",
      },
      {
        img: "/Rawimages/russianspacenterimage43.webp",
        name: "Ishani",
        tag: "Reflexology",
        years: "5 Years · Certified",
        desc: "Ishani is the quiet booking for guests who would rather not have full-body work at all.",
        price: "₹2,200",
        duration: "60 min",
        origin: "indian",
      },
    ],
  },
  "/spa-in-vasant-kunj/": {
    intro:
      "Vasant Kunj guests are our most frequent returners, so these therapists keep notes on file between visits.",
    therapists: [
      {
        img: "/Rawimages/russianspacenterimage23.webp",
        name: "Polina",
        tag: "Aromatherapy",
        years: "6 Years · Certified",
        desc: "Polina remembers which blend worked last time and adjusts rather than starting from scratch each visit.",
        price: "₹3,200",
        duration: "75 min",
        origin: "russian",
      },
      {
        img: "/Rawimages/russianspacenterimage24.webp",
        name: "Ksenia",
        tag: "Prenatal Massage",
        years: "5 Years · Certified",
        desc: "Ksenia is certified in pregnancy massage — side-lying with bolster support, safe from the second trimester.",
        price: "₹3,000",
        duration: "60 min",
        origin: "russian",
      },
      {
        img: "/Rawimages/russianspacenterimage25.webp",
        name: "Angelina",
        tag: "Lymphatic Drainage",
        years: "6 Years · Certified",
        desc: "Angelina works a gentle drainage sequence for swelling and post-flight puffiness, which regulars book seasonally.",
        price: "₹3,000",
        duration: "60 min",
        origin: "russian",
      },
      {
        img: "/Rawimages/russianspacenterimage44.webp",
        name: "Aarti",
        tag: "Couples Suite",
        years: "6 Years · Certified",
        desc: "Aarti runs the couples suite for anniversaries and pre-wedding bookings. Reserve a day ahead for weekends.",
        price: "₹7,500",
        duration: "120 min",
        origin: "indian",
      },
      {
        img: "/Rawimages/russianspacenterimage45.webp",
        name: "Saloni",
        tag: "Swedish Massage",
        years: "5 Years · Certified",
        desc: "Saloni holds the membership regulars — five-session cards, same therapist, same pressure every time.",
        price: "₹2,800",
        duration: "60 min",
        origin: "indian",
      },
      {
        img: "/Rawimages/russianspacenterimage46.webp",
        name: "Mitali",
        tag: "Hot Stone",
        years: "4 Years · Certified",
        desc: "Mitali takes the winter bookings, when the heated-stone hour is the one Vasant Kunj guests ask for by name.",
        price: "₹3,600",
        duration: "75 min",
        origin: "indian",
      },
    ],
  },
  "/spa-in-green-park/": {
    intro:
      "Green Park is the shortest South Delhi run to us, and these are the therapists its early-morning guests book.",
    therapists: [
      {
        img: "/Rawimages/russianspacenterimage26.webp",
        name: "Marina",
        tag: "Aromatherapy",
        years: "7 Years · Certified",
        desc: "Marina takes the 6 AM slot most often — a lighter, waking session rather than one that puts you back to sleep.",
        price: "₹3,000",
        duration: "60 min",
        origin: "russian",
      },
      {
        img: "/Rawimages/russianspacenterimage27.webp",
        name: "Kristina",
        tag: "Swedish Massage",
        years: "5 Years · Certified",
        desc: "Kristina works the before-office hour, timed so you are out of the door inside seventy minutes.",
        price: "₹2,800",
        duration: "60 min",
        origin: "russian",
      },
      {
        img: "/Rawimages/russianspacenterimage28.webp",
        name: "Regina",
        tag: "Russian Banya",
        years: "8 Years · Certified",
        desc: "Regina runs the morning Banya, which is quieter and considerably easier to book than the evening cycle.",
        price: "₹3,500",
        duration: "90 min",
        origin: "russian",
      },
      {
        img: "/Rawimages/russianspacenterimage47.webp",
        name: "Simran",
        tag: "Ayurvedic Abhyanga",
        years: "8 Years · Certified",
        desc: "Simran follows the classical Abhyanga sequence with warm herbal oil and a long scalp finish.",
        price: "₹3,800",
        duration: "90 min",
        origin: "indian",
      },
      {
        img: "/Rawimages/russianspacenterimage48.webp",
        name: "Payal",
        tag: "Reflexology",
        years: "5 Years · Certified",
        desc: "Payal works precise reflex points in the feet — the booking for guests who dislike full-body work.",
        price: "₹2,200",
        duration: "60 min",
        origin: "indian",
      },
      {
        img: "/Rawimages/russianspacenterimage49.webp",
        name: "Tara",
        tag: "Deep Tissue",
        years: "6 Years · Certified",
        desc: "Tara handles the Aurobindo Marg commuters whose necks have not forgiven them for the drive.",
        price: "₹4,400",
        duration: "90 min",
        origin: "indian",
      },
    ],
  },
  "/spa-in-hauz-khas/": {
    intro:
      "The therapeutic end of the team. Hauz Khas guests mostly book for a specific complaint rather than to unwind.",
    therapists: [
      {
        img: "/Rawimages/russianspacenterimage29.webp",
        name: "Galina",
        tag: "Sports Recovery",
        years: "8 Years · Certified",
        desc: "Galina combines deep tissue, trigger-point release and stretching for runners and gym bodies.",
        price: "₹3,600",
        duration: "90 min",
        origin: "russian",
      },
      {
        img: "/Rawimages/russianspacenterimage30.webp",
        name: "Oksana",
        tag: "Deep Tissue",
        years: "6 Years · Certified",
        desc: "Oksana confirms pressure before she starts and holds it — no drifting into a lighter stroke halfway through.",
        price: "₹4,400",
        duration: "90 min",
        origin: "russian",
      },
      {
        img: "/Rawimages/russianspacenterimage31.webp",
        name: "Evgenia",
        tag: "Hot Stone",
        years: "5 Years · Certified",
        desc: "Evgenia uses heat to open a muscle before working it, which suits guests who find deep tissue too sharp cold.",
        price: "₹3,600",
        duration: "75 min",
        origin: "russian",
      },
      {
        img: "/Rawimages/russianspacenterimage50.webp",
        name: "Manisha",
        tag: "Thai Massage",
        years: "6 Years · Certified",
        desc: "Manisha works oil-free acupressure and assisted stretching. Guests leave lengthened rather than drowsy.",
        price: "₹3,200",
        duration: "75 min",
        origin: "indian",
      },
      {
        img: "/Rawimages/russianspacenterimage51.webp",
        name: "Lavanya",
        tag: "Sports Recovery",
        years: "5 Years · Certified",
        desc: "Lavanya takes the Deer Park running crowd — calves, IT band, hip flexors, in that order.",
        price: "₹3,600",
        duration: "90 min",
        origin: "indian",
      },
      {
        img: "/Rawimages/russianspacenterimage52.webp",
        name: "Vaishali",
        tag: "Reflexology",
        years: "7 Years · Certified",
        desc: "Vaishali works reflex points for guests on their feet all day, which in Hauz Khas is most of the hospitality trade.",
        price: "₹2,200",
        duration: "60 min",
        origin: "indian",
      },
    ],
  },
  "/spa-in-saket/": {
    intro:
      "Saket guests drive the furthest, so they tend to book the long formats. These are the therapists who run them.",
    therapists: [
      {
        img: "/Rawimages/russianspacenterimage32.webp",
        name: "Lidia",
        tag: "Royal Signature",
        years: "9 Years · Certified",
        desc: "Lidia runs the full ritual end to end — scrub, ninety-minute massage, scalp and foot work, then Banya.",
        price: "₹8,500",
        duration: "150 min",
        origin: "russian",
      },
      {
        img: "/Rawimages/russianspacenterimage33.webp",
        name: "Tamara",
        tag: "Couples Banya",
        years: "7 Years · Certified",
        desc: "Tamara leads the long couples format, which is what most Saket guests cross the city for.",
        price: "₹9,500",
        duration: "150 min",
        origin: "russian",
      },
      {
        img: "/Rawimages/russianspacenterimage34.webp",
        name: "Nina",
        tag: "Russian Banya",
        years: "6 Years · Certified",
        desc: "Nina takes the standalone Banya bookings for guests who want the ritual without the full ritual day.",
        price: "₹3,500",
        duration: "90 min",
        origin: "russian",
      },
      {
        img: "/Rawimages/russianspacenterimage53.webp",
        name: "Ritika",
        tag: "Couples Suite",
        years: "7 Years · Certified",
        desc: "Ritika runs the two-therapist suite — the booking Saket guests make when the drive has to be worth it.",
        price: "₹7,500",
        duration: "120 min",
        origin: "indian",
      },
      {
        img: "/Rawimages/russianspacenterimage54.webp",
        name: "Swati",
        tag: "Hot Stone",
        years: "5 Years · Certified",
        desc: "Swati pairs heated basalt with deep tissue for guests who want the longer, warmer version of both.",
        price: "₹3,600",
        duration: "75 min",
        origin: "indian",
      },
      {
        img: "/Rawimages/russianspacenterimage55.webp",
        name: "Rupali",
        tag: "Aromatherapy",
        years: "6 Years · Certified",
        desc: "Rupali builds the oil blend into the longer formats so the scent carries through the whole afternoon.",
        price: "₹3,200",
        duration: "75 min",
        origin: "indian",
      },
    ],
  },
  "/spa-in-karol-bagh/": {
    intro:
      "Karol Bagh guests come to us for what a room above a shop cannot offer — licensing, a private room with a door, and a full team.",
    therapists: [
      {
        img: "/Rawimages/russianspacenterimage35.webp",
        name: "Raisa",
        tag: "Russian Banya",
        years: "8 Years · Certified",
        desc: "Raisa runs the Banya cycle in a wood-lined room built for it, not a converted steam cabinet.",
        price: "₹3,500",
        duration: "90 min",
        origin: "russian",
      },
      {
        img: "/Rawimages/russianspacenterimage36.webp",
        name: "Zoya",
        tag: "Swedish Massage",
        years: "6 Years · Certified",
        desc: "Zoya takes most first visits from Karol Bagh — a private room, and the full advertised hour on the table.",
        price: "₹2,800",
        duration: "60 min",
        origin: "russian",
      },
      {
        img: "/Rawimages/russianspacenterimage37.webp",
        name: "Vasilisa",
        tag: "Deep Tissue",
        years: "7 Years · Certified",
        desc: "Vasilisa works chronic tension for guests who spend the day standing behind a counter.",
        price: "₹4,400",
        duration: "90 min",
        origin: "russian",
      },
      {
        img: "/Rawimages/russianspacenterimage56.webp",
        name: "Preeti",
        tag: "Deep Tissue",
        years: "7 Years · Certified",
        desc: "Preeti handles the Ajmal Khan Road traders whose shoulders have carried a shop for twenty years.",
        price: "₹4,400",
        duration: "90 min",
        origin: "indian",
      },
      {
        img: "/Rawimages/russianspacenterimage57.webp",
        name: "Sakshi",
        tag: "Couples Suite",
        years: "5 Years · Certified",
        desc: "Sakshi runs couples bookings for guests who want a suite with a door rather than a curtained partition.",
        price: "₹7,500",
        duration: "120 min",
        origin: "indian",
      },
      {
        img: "/Rawimages/russianspacenterimage58.webp",
        name: "Gauri",
        tag: "Aromatherapy",
        years: "6 Years · Certified",
        desc: "Gauri works a calming blend for guests arriving straight off the Ring Road at the end of a trading day.",
        price: "₹3,000",
        duration: "60 min",
        origin: "indian",
      },
    ],
  },
  "/spa-in-gurugram/": {
    intro:
      "Gurugram guests arrive late, once everything on their side of NH-48 has shut. These therapists work those hours.",
    therapists: [
      {
        img: "/Rawimages/russianspacenterimage38.webp",
        name: "Vlada",
        tag: "Late-Night Banya",
        years: "7 Years · Certified",
        desc: "Vlada takes the 1 AM Banya bookings — steam, venik and a cold plunge reset the body clock faster than lying awake.",
        price: "₹3,500",
        duration: "90 min",
        origin: "russian",
      },
      {
        img: "/Rawimages/russianspacenterimage39.webp",
        name: "Zlata",
        tag: "Deep Tissue",
        years: "6 Years · Certified",
        desc: "Zlata works the Cyber City desk pattern: locked shoulders, stiff neck, lower back that has not moved since Monday.",
        price: "₹4,400",
        duration: "90 min",
        origin: "russian",
      },
      {
        img: "/Rawimages/russianspacenterimage40.webp",
        name: "Arina",
        tag: "Sports Recovery",
        years: "5 Years · Certified",
        desc: "Arina handles gym bodies after a late session, when nothing in Gurugram is open to work on them.",
        price: "₹3,600",
        duration: "90 min",
        origin: "russian",
      },
      {
        img: "/Rawimages/russianspacenterimage59.webp",
        name: "Komal",
        tag: "Sports Recovery",
        years: "6 Years · Certified",
        desc: "Komal treats gym and desk bodies in the same hour: shoulders, lower back, hip flexors.",
        price: "₹3,600",
        duration: "90 min",
        origin: "indian",
      },
      {
        img: "/Rawimages/russianspacenterimage60.webp",
        name: "Jyoti",
        tag: "Aromatherapy",
        years: "5 Years · Certified",
        desc: "Jyoti works a vetiver and lavender blend slowly, timed for guests who need to be asleep within the hour.",
        price: "₹3,000",
        duration: "60 min",
        origin: "indian",
      },
      {
        img: "/Rawimages/russianspacenterimage61.webp",
        name: "Prerna",
        tag: "Swedish Massage",
        years: "4 Years · Certified",
        desc: "Prerna takes the midnight walk-ins — the full hour, at the same rate as any other time of day.",
        price: "₹2,800",
        duration: "60 min",
        origin: "indian",
      },
    ],
  },
};

export function areaTherapistsFor(path: string): AreaRoster | null {
  return AREA_THERAPISTS[path] ?? null;
}
