import type { Faq } from "../components/FaqAccordion";

export type Shot = {
  src: string;
  /** Descriptive alt text — this is what image search actually indexes. */
  alt: string;
  /** Short human caption shown on hover and under the lightbox. */
  caption: string;
  category: CategoryId;
  width: number;
  height: number;
};

export type CategoryId = "spa" | "team";

export const CATEGORIES: { id: CategoryId; label: string }[] = [
  { id: "spa", label: "The Spa" },
  { id: "team", label: "Our Team" },
];

/**
 * Every photo carries its true pixel dimensions so the browser reserves the
 * right box before the file arrives — no layout shift, which is a Core Web
 * Vitals input and therefore a ranking input.
 *
 * The gallery is an index of the site's photography, so images here also
 * appear on the pages they illustrate. That is what a gallery is for and is
 * not duplicate content.
 */
export const SHOTS: Shot[] = [
  {
    src: "/home_images/mahipalpurspa2.jpg",
    alt: "Wood-lined Russian Banya steam room at Russian Spa Centre, Mahipalpur",
    caption: "The Banya steam room, held between 70 and 90°C",
    category: "spa",
    width: 1200,
    height: 1800,
  },
  {
    src: "/home_images/mahipalpurspa15.png",
    alt: "Private massage treatment room with fresh linen at Russian Spa Centre, Mahipalpur",
    caption: "A private treatment room, reset between every guest",
    category: "spa",
    width: 1536,
    height: 1024,
  },
  {
    src: "/home_images/mahipalpurspa150.jpg",
    alt: "Relaxation lounge at Russian Spa Centre, Defence Enclave, Mahipalpur",
    caption: "The relaxation lounge, where a session winds down",
    category: "spa",
    width: 1200,
    height: 1800,
  },
  {
    src: "/Rawimages/russianspacenterimage1.webp",
    alt: "Therapist at Russian Spa Centre, Mahipalpur",
    caption: "One of our therapists at Defence Enclave",
    category: "team",
    width: 720,
    height: 1280,
  },
  {
    src: "/Rawimages/russianspacenterimage2.webp",
    alt: "Spa therapist at our Defence Enclave premises, Mahipalpur",
    caption: "Part of the team at Russian Spa Centre",
    category: "team",
    width: 720,
    height: 1280,
  },
  {
    src: "/Rawimages/russianspacenterimage3.webp",
    alt: "Member of the therapy team at Russian Spa Centre, New Delhi",
    caption: "A therapist from our Mahipalpur team",
    category: "team",
    width: 899,
    height: 1096,
  },
  {
    src: "/Rawimages/russianspacenterimage4.webp",
    alt: "Massage therapist at Russian Spa Centre near IGI Airport",
    caption: "Our therapy team, Mahipalpur",
    category: "team",
    width: 720,
    height: 1280,
  },
  {
    src: "/Rawimages/russianspacenterimage5.webp",
    alt: "Therapist at our 24-hour spa in Mahipalpur, Delhi NCR",
    caption: "One of our therapists at Defence Enclave",
    category: "team",
    width: 725,
    height: 1280,
  },
  {
    src: "/Rawimages/russianspacenterimage6.webp",
    alt: "Spa and body massage therapist, Russian Spa Centre Mahipalpur",
    caption: "Part of the team at Russian Spa Centre",
    category: "team",
    width: 725,
    height: 1280,
  },
  {
    src: "/Rawimages/russianspacenterimage7.webp",
    alt: "Therapist at Russian Spa Centre, Mahipalpur",
    caption: "A therapist from our Mahipalpur team",
    category: "team",
    width: 720,
    height: 1280,
  },
  {
    src: "/Rawimages/russianspacenterimage8.webp",
    alt: "Spa therapist at our Defence Enclave premises, Mahipalpur",
    caption: "Our therapy team, Mahipalpur",
    category: "team",
    width: 720,
    height: 1280,
  },
  {
    src: "/Rawimages/russianspacenterimage9.webp",
    alt: "Member of the therapy team at Russian Spa Centre, New Delhi",
    caption: "One of our therapists at Defence Enclave",
    category: "team",
    width: 742,
    height: 1280,
  },
  {
    src: "/Rawimages/russianspacenterimage10.webp",
    alt: "Massage therapist at Russian Spa Centre near IGI Airport",
    caption: "Part of the team at Russian Spa Centre",
    category: "team",
    width: 720,
    height: 1280,
  },
  {
    src: "/Rawimages/russianspacenterimage11.webp",
    alt: "Therapist at our 24-hour spa in Mahipalpur, Delhi NCR",
    caption: "A therapist from our Mahipalpur team",
    category: "team",
    width: 720,
    height: 1280,
  },
  {
    src: "/Rawimages/russianspacenterimage12.webp",
    alt: "Spa and body massage therapist, Russian Spa Centre Mahipalpur",
    caption: "Our therapy team, Mahipalpur",
    category: "team",
    width: 720,
    height: 1280,
  },
  {
    src: "/Rawimages/russianspacenterimage13.webp",
    alt: "Therapist at Russian Spa Centre, Mahipalpur",
    caption: "One of our therapists at Defence Enclave",
    category: "team",
    width: 720,
    height: 1280,
  },
  {
    src: "/Rawimages/russianspacenterimage14.webp",
    alt: "Spa therapist at our Defence Enclave premises, Mahipalpur",
    caption: "Part of the team at Russian Spa Centre",
    category: "team",
    width: 1036,
    height: 1280,
  },
  {
    src: "/Rawimages/russianspacenterimage15.webp",
    alt: "Member of the therapy team at Russian Spa Centre, New Delhi",
    caption: "A therapist from our Mahipalpur team",
    category: "team",
    width: 948,
    height: 1280,
  },
  {
    src: "/Rawimages/russianspacenterimage16.webp",
    alt: "Massage therapist at Russian Spa Centre near IGI Airport",
    caption: "Our therapy team, Mahipalpur",
    category: "team",
    width: 720,
    height: 1280,
  },
  {
    src: "/Rawimages/russianspacenterimage17.webp",
    alt: "Therapist at our 24-hour spa in Mahipalpur, Delhi NCR",
    caption: "One of our therapists at Defence Enclave",
    category: "team",
    width: 854,
    height: 1280,
  },
  {
    src: "/Rawimages/russianspacenterimage18.webp",
    alt: "Spa and body massage therapist, Russian Spa Centre Mahipalpur",
    caption: "Part of the team at Russian Spa Centre",
    category: "team",
    width: 877,
    height: 1280,
  },
  {
    src: "/Rawimages/russianspacenterimage19.webp",
    alt: "Therapist at Russian Spa Centre, Mahipalpur",
    caption: "A therapist from our Mahipalpur team",
    category: "team",
    width: 768,
    height: 1280,
  },
  {
    src: "/Rawimages/russianspacenterimage20.webp",
    alt: "Spa therapist at our Defence Enclave premises, Mahipalpur",
    caption: "Our therapy team, Mahipalpur",
    category: "team",
    width: 576,
    height: 1103,
  },
  {
    src: "/Rawimages/russianspacenterimage21.webp",
    alt: "Member of the therapy team at Russian Spa Centre, New Delhi",
    caption: "One of our therapists at Defence Enclave",
    category: "team",
    width: 835,
    height: 1186,
  },
  {
    src: "/Rawimages/russianspacenterimage22.webp",
    alt: "Massage therapist at Russian Spa Centre near IGI Airport",
    caption: "Part of the team at Russian Spa Centre",
    category: "team",
    width: 720,
    height: 1280,
  },
  {
    src: "/Rawimages/russianspacenterimage23.webp",
    alt: "Therapist at our 24-hour spa in Mahipalpur, Delhi NCR",
    caption: "A therapist from our Mahipalpur team",
    category: "team",
    width: 590,
    height: 1280,
  },
  {
    src: "/Rawimages/russianspacenterimage24.webp",
    alt: "Spa and body massage therapist, Russian Spa Centre Mahipalpur",
    caption: "Our therapy team, Mahipalpur",
    category: "team",
    width: 958,
    height: 1280,
  },
  {
    src: "/Rawimages/russianspacenterimage25.webp",
    alt: "Therapist at Russian Spa Centre, Mahipalpur",
    caption: "One of our therapists at Defence Enclave",
    category: "team",
    width: 960,
    height: 1280,
  },
  {
    src: "/Rawimages/russianspacenterimage26.webp",
    alt: "Spa therapist at our Defence Enclave premises, Mahipalpur",
    caption: "Part of the team at Russian Spa Centre",
    category: "team",
    width: 1080,
    height: 1433,
  },
  {
    src: "/Rawimages/russianspacenterimage27.webp",
    alt: "Member of the therapy team at Russian Spa Centre, New Delhi",
    caption: "A therapist from our Mahipalpur team",
    category: "team",
    width: 1079,
    height: 1426,
  },
  {
    src: "/Rawimages/russianspacenterimage28.webp",
    alt: "Massage therapist at Russian Spa Centre near IGI Airport",
    caption: "Our therapy team, Mahipalpur",
    category: "team",
    width: 1080,
    height: 1398,
  },
  {
    src: "/Rawimages/russianspacenterimage29.webp",
    alt: "Therapist at our 24-hour spa in Mahipalpur, Delhi NCR",
    caption: "One of our therapists at Defence Enclave",
    category: "team",
    width: 918,
    height: 1600,
  },
  {
    src: "/Rawimages/russianspacenterimage30.webp",
    alt: "Spa and body massage therapist, Russian Spa Centre Mahipalpur",
    caption: "Part of the team at Russian Spa Centre",
    category: "team",
    width: 916,
    height: 1600,
  },
  {
    src: "/Rawimages/russianspacenterimage31.webp",
    alt: "Therapist at Russian Spa Centre, Mahipalpur",
    caption: "A therapist from our Mahipalpur team",
    category: "team",
    width: 1080,
    height: 1571,
  },
  {
    src: "/Rawimages/russianspacenterimage32.webp",
    alt: "Spa therapist at our Defence Enclave premises, Mahipalpur",
    caption: "Our therapy team, Mahipalpur",
    category: "team",
    width: 896,
    height: 1100,
  },
  {
    src: "/Rawimages/russianspacenterimage33.webp",
    alt: "Member of the therapy team at Russian Spa Centre, New Delhi",
    caption: "One of our therapists at Defence Enclave",
    category: "team",
    width: 733,
    height: 1280,
  },
  {
    src: "/Rawimages/russianspacenterimage34.webp",
    alt: "Massage therapist at Russian Spa Centre near IGI Airport",
    caption: "Part of the team at Russian Spa Centre",
    category: "team",
    width: 911,
    height: 1600,
  },
  {
    src: "/Rawimages/russianspacenterimage35.webp",
    alt: "Therapist at our 24-hour spa in Mahipalpur, Delhi NCR",
    caption: "A therapist from our Mahipalpur team",
    category: "team",
    width: 730,
    height: 1280,
  },
  {
    src: "/Rawimages/russianspacenterimage36.webp",
    alt: "Spa and body massage therapist, Russian Spa Centre Mahipalpur",
    caption: "Our therapy team, Mahipalpur",
    category: "team",
    width: 905,
    height: 1600,
  },
  {
    src: "/Rawimages/russianspacenterimage37.webp",
    alt: "Therapist at Russian Spa Centre, Mahipalpur",
    caption: "One of our therapists at Defence Enclave",
    category: "team",
    width: 727,
    height: 1280,
  },
  {
    src: "/Rawimages/russianspacenterimage38.webp",
    alt: "Spa therapist at our Defence Enclave premises, Mahipalpur",
    caption: "Part of the team at Russian Spa Centre",
    category: "team",
    width: 743,
    height: 1600,
  },
  {
    src: "/Rawimages/russianspacenterimage39.webp",
    alt: "Member of the therapy team at Russian Spa Centre, New Delhi",
    caption: "A therapist from our Mahipalpur team",
    category: "team",
    width: 962,
    height: 1598,
  },
  {
    src: "/Rawimages/russianspacenterimage40.webp",
    alt: "Massage therapist at Russian Spa Centre near IGI Airport",
    caption: "Our therapy team, Mahipalpur",
    category: "team",
    width: 727,
    height: 1280,
  },
  {
    src: "/Rawimages/russianspacenterimage41.webp",
    alt: "Therapist at our 24-hour spa in Mahipalpur, Delhi NCR",
    caption: "One of our therapists at Defence Enclave",
    category: "team",
    width: 899,
    height: 1600,
  },
  {
    src: "/Rawimages/russianspacenterimage42.webp",
    alt: "Spa and body massage therapist, Russian Spa Centre Mahipalpur",
    caption: "Part of the team at Russian Spa Centre",
    category: "team",
    width: 1079,
    height: 1426,
  },
  {
    src: "/Rawimages/russianspacenterimage43.webp",
    alt: "Therapist at Russian Spa Centre, Mahipalpur",
    caption: "A therapist from our Mahipalpur team",
    category: "team",
    width: 905,
    height: 1600,
  },
  {
    src: "/Rawimages/russianspacenterimage44.webp",
    alt: "Spa therapist at our Defence Enclave premises, Mahipalpur",
    caption: "Our therapy team, Mahipalpur",
    category: "team",
    width: 911,
    height: 1599,
  },
  {
    src: "/Rawimages/russianspacenterimage45.webp",
    alt: "Member of the therapy team at Russian Spa Centre, New Delhi",
    caption: "One of our therapists at Defence Enclave",
    category: "team",
    width: 900,
    height: 1600,
  },
  {
    src: "/Rawimages/russianspacenterimage46.webp",
    alt: "Massage therapist at Russian Spa Centre near IGI Airport",
    caption: "Part of the team at Russian Spa Centre",
    category: "team",
    width: 719,
    height: 1280,
  },
  {
    src: "/Rawimages/russianspacenterimage47.webp",
    alt: "Therapist at our 24-hour spa in Mahipalpur, Delhi NCR",
    caption: "A therapist from our Mahipalpur team",
    category: "team",
    width: 895,
    height: 1599,
  },
  {
    src: "/Rawimages/russianspacenterimage48.webp",
    alt: "Spa and body massage therapist, Russian Spa Centre Mahipalpur",
    caption: "Our therapy team, Mahipalpur",
    category: "team",
    width: 1080,
    height: 1398,
  },
  {
    src: "/Rawimages/russianspacenterimage49.webp",
    alt: "Therapist at Russian Spa Centre, Mahipalpur",
    caption: "One of our therapists at Defence Enclave",
    category: "team",
    width: 885,
    height: 1600,
  },
  {
    src: "/Rawimages/russianspacenterimage50.webp",
    alt: "Spa therapist at our Defence Enclave premises, Mahipalpur",
    caption: "Part of the team at Russian Spa Centre",
    category: "team",
    width: 1069,
    height: 1600,
  },
  {
    src: "/Rawimages/russianspacenterimage51.webp",
    alt: "Member of the therapy team at Russian Spa Centre, New Delhi",
    caption: "A therapist from our Mahipalpur team",
    category: "team",
    width: 1080,
    height: 1056,
  },
  {
    src: "/Rawimages/russianspacenterimage52.webp",
    alt: "Massage therapist at Russian Spa Centre near IGI Airport",
    caption: "Our therapy team, Mahipalpur",
    category: "team",
    width: 909,
    height: 1600,
  },
  {
    src: "/Rawimages/russianspacenterimage53.webp",
    alt: "Therapist at our 24-hour spa in Mahipalpur, Delhi NCR",
    caption: "One of our therapists at Defence Enclave",
    category: "team",
    width: 1040,
    height: 1600,
  },
  {
    src: "/Rawimages/russianspacenterimage54.webp",
    alt: "Spa and body massage therapist, Russian Spa Centre Mahipalpur",
    caption: "Part of the team at Russian Spa Centre",
    category: "team",
    width: 916,
    height: 1600,
  },
  {
    src: "/Rawimages/russianspacenterimage55.webp",
    alt: "Therapist at Russian Spa Centre, Mahipalpur",
    caption: "A therapist from our Mahipalpur team",
    category: "team",
    width: 920,
    height: 1600,
  },
  {
    src: "/Rawimages/russianspacenterimage56.webp",
    alt: "Spa therapist at our Defence Enclave premises, Mahipalpur",
    caption: "Our therapy team, Mahipalpur",
    category: "team",
    width: 914,
    height: 1600,
  },
  {
    src: "/Rawimages/russianspacenterimage57.webp",
    alt: "Member of the therapy team at Russian Spa Centre, New Delhi",
    caption: "One of our therapists at Defence Enclave",
    category: "team",
    width: 727,
    height: 1280,
  },
  {
    src: "/Rawimages/russianspacenterimage58.webp",
    alt: "Massage therapist at Russian Spa Centre near IGI Airport",
    caption: "Part of the team at Russian Spa Centre",
    category: "team",
    width: 725,
    height: 1280,
  },
  {
    src: "/Rawimages/russianspacenterimage59.webp",
    alt: "Therapist at our 24-hour spa in Mahipalpur, Delhi NCR",
    caption: "A therapist from our Mahipalpur team",
    category: "team",
    width: 730,
    height: 1280,
  },
  {
    src: "/Rawimages/russianspacenterimage60.webp",
    alt: "Spa and body massage therapist, Russian Spa Centre Mahipalpur",
    caption: "Our therapy team, Mahipalpur",
    category: "team",
    width: 719,
    height: 1280,
  },
  {
    src: "/Rawimages/russianspacenterimage61.webp",
    alt: "Therapist at Russian Spa Centre, Mahipalpur",
    caption: "One of our therapists at Defence Enclave",
    category: "team",
    width: 723,
    height: 1280,
  },
];

export const GALLERY_FAQS: Faq[] = [
  {
    q: "Are these photos of the actual Mahipalpur spa?",
    a: "The Banya, treatment-room and lounge photographs are of our own Defence Enclave premises in Mahipalpur. The team photographs under \"Our Team\" are portraits of our therapists rather than pictures of the facilities. Nothing here is stock photography of someone else's spa.",
  },
  {
    q: "Can I see a room before I book?",
    a: "Absolutely. Walk in at any hour and ask at reception — we are happy to show you the treatment rooms, the Banya and the lounge before you decide anything. No appointment is needed for a look around.",
  },
  {
    q: "Are photographs allowed inside the spa?",
    a: "For the privacy of other guests, personal photography is not permitted in the treatment wing, the Banya or the changing areas. Reception and the lounge are fine. This is why our own photos are taken outside operating peaks with no guests present.",
  },
  {
    q: "Is every treatment room private?",
    a: "Yes — every treatment happens in a fully enclosed private room with a door, not behind a curtain partition. Couples suites are separate rooms sized for two tables.",
  },
  {
    q: "How often are the rooms cleaned?",
    a: "Linens are changed and the room is disinfected to hospital-grade standards after every single guest, not on a schedule. The wet areas and Banya are deep-cleaned on a rolling cycle through the day and night.",
  },
];
